(function(){var h={},mt={},c={id:"6387fcb06c7f33ad6787ab913d4e6d10",dm:["swiper.com.cn","tweenmax.com.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:["%5b%22https%3a%5c%2f%5c%2fswiper.com.cn%5c%2findex.html%22%2c%22https%3a%5c%2f%5c%2fswiper.com.cn%5c%2fapi%22%5d"],nv:0,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'D4CF1DC56BF97BED',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var u=void 0,v=!0,x=null,y=!1;mt.cookie={};mt.cookie.set=function(a,b,d){var f;d.R&&(f=new Date,f.setTime(f.getTime()+d.R));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(f?"; expires="+f.toGMTString():"")+(d.Qc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:x};
mt.cookie.sc=function(a,b){try{var d="Hm_ck_"+ +new Date;mt.cookie.set(d,"is-cookie-enabled",{domain:a,path:b,R:u});var f="is-cookie-enabled"===mt.cookie.get(d)?"1":"0";mt.cookie.set(d,"",{domain:a,path:b,R:-1});return f}catch(e){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.cb=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.H=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.G=function(a,b){var d=y;if(a==x||!mt.lang.d(a,"Array")||b===u)return d;if(Array.prototype.indexOf)d=-1!==a.indexOf(b);else for(var f=0;f<a.length;f++)if(a[f]===b){d=v;break}return d};mt.url={};mt.url.m=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:x};
mt.url.Mc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:x};mt.url.Vb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):x};mt.url.L=function(a){return(a=mt.url.Vb(a))?a.replace(/:\d+$/,""):a};mt.url.Fa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):x};
(function(){var a=mt.lang,b=mt.url;mt.f={};mt.f.Wa=function(d){return document.getElementById(d)};mt.f.Da=function(d){if(!d)return x;try{d=String(d);if(0===d.indexOf("!HMCQ!"))return d;if(0===d.indexOf("!HMCC!"))return document.querySelector(d.substring(6,d.length));for(var a=d.split(">"),e=document.body,b=a.length-1;0<=b;b--)if(-1<a[b].indexOf("#")){var g=a[b].split("#")[1];(e=document.getElementById(g))||(e=document.getElementById(decodeURIComponent(g)));a=a.splice(b+1,a.length-(b+1));break}for(d=
0;e&&d<a.length;){var l=String(a[d]).toLowerCase();if(!("html"===l||"body"===l)){var b=0,n=a[d].match(/\[(\d+)\]/i),g=[];if(n)b=n[1]-1,l=l.split("[")[0];else if(1!==e.childNodes.length){for(var t=0,q=0,r=e.childNodes.length;q<r;q++){var p=e.childNodes[q];1===p.nodeType&&p.nodeName.toLowerCase()===l&&t++;if(1<t)return x}if(1!==t)return x}for(t=0;t<e.childNodes.length;t++)1===e.childNodes[t].nodeType&&e.childNodes[t].nodeName.toLowerCase()===l&&g.push(e.childNodes[t]);if(!g[b])return x;e=g[b]}d++}return e}catch(k){return x}};
mt.f.Fa=function(a,f){var e=[],b=[];if(!a)return b;for(;a.parentNode!=x;){for(var g=0,l=0,n=a.parentNode.childNodes.length,t=0;t<n;t++){var q=a.parentNode.childNodes[t];if(q.nodeName===a.nodeName&&(g++,q===a&&(l=g),0<l&&1<g))break}if((n=""!==a.id)&&f){e.unshift("#"+encodeURIComponent(a.id));break}else n&&(n="#"+encodeURIComponent(a.id),n=0<e.length?n+">"+e.join(">"):n,b.push(n)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+l+"]":""));a=a.parentNode}b.push(e.join(">"));return b};
mt.f.ma=function(a){return(a=mt.f.Fa(a,v))&&a.length?String(a[0]):""};mt.f.Zb=function(a){return mt.f.Fa(a,y)};mt.f.Xa=function(a){var f;for(f="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==f)return a;return x};mt.f.Rb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Ya=function(a){var f={top:0,left:0};if(!a)return f;var e=mt.f.Rb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(f=a.getBoundingClientRect());return{top:f.top+(window.pageYOffset||e.scrollTop)-
(e.clientTop||0),left:f.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.f.getAttribute=function(a,f){var e=a.getAttribute&&a.getAttribute(f)||x;if(!e&&a.attributes&&a.attributes.length)for(var b=a.attributes,g=b.length,l=0;l<g;l++)b[l].nodeName===f&&(e=b[l].nodeValue);return e};mt.f.V=function(a){var b="document";a.tagName!==u&&(b=a.tagName);return b.toLowerCase()};mt.f.bc=function(b){var f="";b.textContent?f=a.trim(b.textContent):b.innerText&&(f=a.trim(b.innerText));f&&(f=f.replace(/\s+/g,
" ").substring(0,255));return f};mt.f.U=function(d,f){var e;a.H(d)&&0===String(d).indexOf("!HMCQ!")?(e=String(d),e=b.m(document.location.href,e.substring(6,e.length))):a.H(d)||(e=mt.f.V(d),"input"===e&&f&&("button"===d.type||"submit"===d.type)?e=a.trim(d.value)||"":"input"===e&&!f&&"password"!==d.type?e=a.trim(d.value)||"":"img"===e?(e=mt.f.getAttribute,e=e(d,"alt")||e(d,"title")||e(d,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.f.bc(d));return String(e||"").substring(0,
255)};(function(){(mt.f.jb=function(){function a(){if(!a.pa){a.pa=v;for(var b=0,e=s.length;b<e;b++)s[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var e=y,s=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,y);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!e)if(e=v,"complete"===document.readyState)a.pa=v;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,y),window.addEventListener("load",a,y);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var l=y;try{l=window.frameElement==x}catch(n){}document.documentElement.doScroll&&l&&b()}})();return function(b){a.pa?b():s.push(b)}}()).pa=y})();return mt.f})();mt.event={};
mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,y)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=y};
(function(){var a=mt.event;mt.g={};mt.g.na=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.Wb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.g.Nc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return y}};mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();
mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.xc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.W=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.M=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.tb=
0;mt.g.ec=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.g.orientation=0;(function(){function b(){var a=0;window.orientation!==u&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==u)&&(a=screen.orientation.angle);mt.g.orientation=a;mt.g.tb=mt.g.ec()}b();a.e(window,"orientationchange",b)})();return mt.g})();mt.w={};mt.w.parse=function(a){return(new Function("return ("+a+")"))()};
mt.w.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(f){switch(typeof f){case "undefined":return"undefined";case "number":return isFinite(f)?String(f):"null";case "string":return a(f);case "boolean":return String(f);
default:if(f===x)return"null";if(f instanceof Array){var e=["["],d=f.length,g,l,n;for(l=0;l<d;l++)switch(n=f[l],typeof n){case "undefined":case "function":case "unknown":break;default:g&&e.push(","),e.push(mt.w.stringify(n)),g=1}e.push("]");return e.join("")}if(f instanceof Date)return'"'+f.getFullYear()+"-"+b(f.getMonth()+1)+"-"+b(f.getDate())+"T"+b(f.getHours())+":"+b(f.getMinutes())+":"+b(f.getSeconds())+'"';g=["{"];l=mt.w.stringify;for(d in f)if(Object.prototype.hasOwnProperty.call(f,d))switch(n=
f[d],typeof n){case "undefined":case "unknown":case "function":break;default:e&&g.push(","),e=1,g.push(l(d)+":"+l(n))}g.push("}");return g.join("")}}}();mt.localStorage={};mt.localStorage.xa=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return y}return v};
mt.localStorage.set=function(a,b,d){var f=new Date;f.setTime(f.getTime()+d||31536E6);try{window.localStorage?(b=f.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.xa()&&(mt.localStorage.l.expires=f.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.xa())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(f){}return x};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.xa())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):x}catch(b){return x}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.pb={};mt.pb.log=function(a,b){var d=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=d;d.onload=function(){d.onload=x;d=window[f]=x;b&&b(a)};d.src=a};mt.Na={};
mt.Na.dc=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
mt.Na.Lc=function(a,b,d,f,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+d+'" height="'+f+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+d+'" height="'+f+'" src="'+b+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};
h.A={lc:"http://tongji.baidu.com/hm-web/welcome/ico",Ma:"hm.baidu.com/hm.gif",Ab:/^(tongji|hmcdn).baidu.com$/,rb:"tongji.baidu.com",ic:"hmmd",jc:"hmpl",Ic:"utm_medium",hc:"hmkw",Kc:"utm_term",fc:"hmci",Hc:"utm_content",kc:"hmsr",Jc:"utm_source",gc:"hmcu",Gc:"utm_campaign",N:0,J:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ra:"https:",Oc:0,Gb:6E5,Pc:6E5,yc:5E3,Hb:5,P:1024,Fb:1,ca:2147483647,qb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
Y:v,Ta:["a","input","button"],Qa:{id:"data-hm-id",ha:"data-hm-class",ga:"data-hm-xpath",content:"data-hm-content",ua:"data-hm-tag",link:"data-hm-link"},Sa:"data-hm-enabled",Ra:"data-hm-disabled",uc:"https://hmcdn.baidu.com/static/tongji/plugins/",ib:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={F:{},e:function(a,d){this.F[a]=this.F[a]||[];this.F[a].push(d)},K:function(a,d){this.F[a]=this.F[a]||[];for(var f=this.F[a].length,e=0;e<f;e++)this.F[a][e](d)}};return h.s=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,d={Qb:function(a){var e;try{e=JSON.parse(decodeURIComponent(a[0]))}catch(b){}return e},eb:function(a,e){var d=h.c&&h.c.b&&h.c.b.u||document.location.href;b.test(a)||(d=d.replace(b,""));a=a.replace(/\/$/,"");d=d.replace(/\/$/,"");e&&(d=d.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+a.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(d)},S:function(b,e){var s=d.Qb(b);if(!a.d(s,"Undefined")){if(a.d(s,"Array")){for(var g=0;g<s.length;g++)if(d.eb(s[g],
e))return v;return y}if(a.d(s,"Object")){var g=[],l;for(l in s)s.hasOwnProperty(l)&&d.eb(l,e)&&(g=g.concat(s[l]));return g}}}};return h.ia=d})();
(function(){function a(a,f){var e=document.createElement("script");e.charset="utf-8";b.d(f,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=x,f()}:e.onload=function(){f()});e.src=a;var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(e,s)}var b=mt.lang;return h.load=a})();
(function(){var a=h.A,b={init:function(){if(""!==c.icon){var b=c.icon.split("|"),f=a.lc+"?s="+c.id,e="https://hmcdn.baidu.com/static"+b[0]+".gif";document.write("swf"===b[1]||"gif"===b[1]?'<a href="'+f+'" target="_blank"><img border="0" src="'+e+'" width="'+b[2]+'" height="'+b[3]+'"></a>':'<a href="'+f+'" target="_blank">'+b[0]+"</a>")}}};h.s.e("pv-b",b.init);return b})();
(function(){var a=mt.cookie,b=mt.localStorage,d=mt.sessionStorage,f={getData:function(e){try{return a.get(e)||d.get(e)||b.get(e)}catch(f){}},setData:function(e,s,g){try{a.set(e,s,{domain:f.T(),path:f.la(),R:g}),g?b.set(e,s,g):d.set(e,s)}catch(l){}},removeData:function(e){try{a.set(e,"",{domain:f.T(),path:f.la(),R:-1}),d.remove(e),b.remove(e)}catch(s){}},Z:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var f=a.indexOf(b);return-1<f&&f+b.length===a.length},qa:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},T:function(){for(var a=document.location.hostname,b=0,g=c.dm.length;b<g;b++)if(f.Z(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},la:function(){for(var a=0,b=c.dm.length;a<b;a++){var g=c.dm[a];if(-1<g.indexOf("/")&&f.qa(document.location.href,g))return g.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.Aa=f})();
(function(){var a=mt.lang,b=mt.w,d=h.Aa,f={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},s=["session","user"],g="Hm_up_"+c.id,l={init:function(){l.pc()},pc:function(){try{var e=b.parse(decodeURIComponent(d.getData(g)));a.d(e,"Object")&&(f.user=e)}catch(t){}},B:function(a){var b={};f[a]!==u&&(b=f[a]);a=this.Ga();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},Ga:function(){for(var a={},b,e=s.length-
1;0<=e;e--){b=f[s[e]];for(var r in b)b.hasOwnProperty(r)&&(a[r]=b[r])}return a},setProperty:function(e,g,d){var r=f[e];if(a.d(r,"Object")&&a.d(g,"Object")){for(var p in g)if(g.hasOwnProperty(p)){var k=a.h(String(p));if(d||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var m=g[p];if(m==x)delete r[k];else{if(a.d(m,"Object")||a.d(m,"Array"))m=b.stringify(m);m=a.h(String(m));l.rc(e,k,m)&&(r[k]={value:m,scope:l.$a(e)})}}}"user"===e&&l.Ka()}},o:function(b){b!==u&&("userId"===
b&&a.d(f.user,"Object")?(delete f.user.uid_,l.Ka()):"user"===b&&a.d(f.user,"Object")?(b=f.user.uid_,f.user=b===u?{}:{uid_:b},l.Ka()):f[b]!==u&&(f[b]={}))},Ka:function(){try{d.setData(g,encodeURIComponent(b.stringify(f.user)),c.age)}catch(a){}},rc:function(a,b,e){var r=v,g=f[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)r=y;else{var k=g[b];g[b]={value:e,scope:l.$a(a)};a=l.O(l.B(a));2048<encodeURIComponent(a).length&&(k!==u?g[b]=k:delete g[b],r=y)}return r},
O:function(a){var b=[],e,f;for(f in a)a.hasOwnProperty(f)&&(e=[f,a[f].value],(1===a[f].scope||2===a[f].scope)&&e.push(a[f].scope),b.push(e.join("*")));return b.join("!")},$a:function(a){a=e[a];return a!==u?a:e.others}};return h.Q=l})();
(function(){var a=mt.f,b=mt.lang,d=h.s,f=h.ia,e=h.Q,s=e.O;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var g={hb:{},va:{},init:function(){for(var a,e=f.S(c.cptrk)||[],d=0;d<e.length;d++)if(a=e[d],a.a!==u&&b.d(a.a,"Object")){a=a.a;for(var q in a)a.hasOwnProperty(q)&&(g.va[q]=String(a[q]))}},gb:function(){var b,e,f;for(f in g.va)if(g.va.hasOwnProperty(f)&&g.hb[f]===u&&(b=g.va[f],b=a.Da(b)))e=e===u?{}:e,e[f]=a.U(b,y),g.hb[f]=v;return e},Ha:function(){var a=g.gb();a&&g.Ac(a)},nc:function(){"MutationObserver"in
window?(new MutationObserver(g.Ha)).observe(document.body,{childList:v,subtree:v}):window.setInterval(g.Ha,15E3)},Ac:function(a){if(b.d(a,"Object"))try{e.setProperty("pageview",a);var f=h.c.b.p,g=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=s(e.B("pageview"));h.c.i();h.c.b.p=f;h.c.b.ep=g;e.o("pageview")}catch(d){}}};g.init();d.e("pv-b",function(){var a=g.gb();a&&e.setProperty("pageview",a)});g.nc();a.jb(g.Ha)}})();
(function(){var a=mt.lang,b=mt.f,d=h.ia,f={ka:function(a,s){return function(g){var l=g.target||g.srcElement;if(l){var n=d.S(s)||[],t=l.getAttribute(a.wa);g=g.clientX+":"+g.clientY;if(t&&t===g)l.removeAttribute(a.wa);else if(0<n.length&&(l=b.Zb(l))&&l.length)if(n=l.length,t=l[l.length-1],1E4>n*t.split(">").length)for(t=0;t<n;t++)f.ob(a,l[t]);else f.ob(a,t)}}},ob:function(b,f){for(var g={},d=String(f).split(">").length,n=0;n<d;n++)g[f]="",f=f.substring(0,f.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.Ua)&&
b.Ua(g)},wc:function(a,b){return function(f){(f.target||f.srcElement).setAttribute(a.wa,f.clientX+":"+f.clientY);a&&a.z&&(b?a.z(b):a.z("#"+encodeURIComponent(this.id),f.type))}}};return h.Ca=f})();
(function(){var a=mt.f,b=mt.event,d=mt.lang,f=h.A,e=h.ia,s=h.Ca,g=h.Q,l=g.O,n={wa:"HM_ce",vb:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",s.ka(n,c.cetrk));for(var f=e.S(c.cetrk)||[],d=0,g=f.length;d<g;d++){var p=f[d],k=p.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.Wa(k))&&b.e(k,"click",s.wc(n,p)))}}},Ua:function(a){for(var b=e.S(c.cetrk)||[],f=0;f<b.length;f++){var d=b[f],k=n.Tb(d.p,a);k&&n.z(d,k)}},Tb:function(a,b){a=String(a);if(0<a.indexOf("*")){var f=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in b)if(b.hasOwnProperty(e)&&f.test(e))return e;return x}return b.hasOwnProperty(a)?a:x},z:function(b,f){h.c.b.et=7;var e=b&&b.k||"",e=d.h(e),p={};if(b&&b.a&&d.d(b.a,"Object")){var k=b.a,m;for(m in k)if(k.hasOwnProperty(m)){var w=n.$b(k[m]||"",f),w=w?a.U(w,y):"";p[m]=w}}p=n.Ob(p,f||b&&b.p);p._iden=e;g.setProperty("customEvent",p);h.c.b.ep="";h.c.b.p=l(g.B("customEvent"));h.c.i();h.c.b.p="";g.o("customEvent")},
Ob:function(b,e){var d=a.Da(e),g=f.Qa;d&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(d,g.id)||a.getAttribute(d,"id")||"",b.ec_=a.getAttribute(d,g.ha)||a.getAttribute(d,"class")||"",b.ex_=a.getAttribute(d,g.ga)||a.ma(d),b.en_=a.getAttribute(d,g.content)||a.U(d,v),b.et_=a.getAttribute(d,g.ua)||a.V(d),b.el_=a.getAttribute(d,g.link)||a.getAttribute(d,"href")||""):(b.ex_=a.getAttribute(d,g.ga)||a.ma(d),b.en_=a.getAttribute(d,g.content)||a.U(d,v)));return b},$b:function(b,f){b=String(b);f=String(f);if(0<
b.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(f);b=b.replace("*",e?e[1]:"1")}return a.Da(b)}};h.s.e("pv-b",n.vb);return n})();
(function(){var a=mt.f,b=mt.lang,d=mt.event,f=mt.g,e=h.A,s=h.ia,g=[],l={ub:function(){c.ctrk&&0<c.ctrk.length&&(d.e(document,"mouseup",l.Eb()),d.e(window,"unload",function(){l.sa()}),setInterval(function(){l.sa()},e.Gb))},Eb:function(){return function(a){if(s.S(c.ctrk,v)&&(a=l.Pb(a),""!==a)){var b=(e.ra+"//"+e.Ma+"?"+h.c.nb().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(e.ca+"").length>e.P||(b+encodeURIComponent(g.join("!")+(g.length?"!":"")).length+(e.ca+"").length>e.P&&l.sa(),g.push(a),
(g.length>=e.Hb||/\*a\*/.test(a))&&l.sa())}}},Pb:function(d){var g=d.target||d.srcElement;if(0===e.Fb){var q=(g.tagName||"").toLowerCase();if("embed"==q||"object"==q)return""}var r;f.na?(r=Math.max(document.documentElement.scrollTop,document.body.scrollTop),q=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),q=d.clientX+q,r=d.clientY+r):(q=d.pageX,r=d.pageY);d=l.Xb(d,g,q,r);var p=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:q-=
p/2;break;case 2:q-=p}p=[];p.push(q);p.push(r);p.push(d.ba);p.push(d.da);p.push(d.vc);p.push(b.h(d.tc));p.push(d.fa);p.push(d.X);(g="a"===(g.tagName||"").toLowerCase()?g:a.Xa(g))?(p.push("a"),p.push(b.h(encodeURIComponent(g.href)))):p.push("b");return p.join("*")},Xb:function(e,d,g,r){e=a.ma(d);var p=0,k=0,m=0,w=0;if(d&&(p=d.offsetWidth||d.clientWidth,k=d.offsetHeight||d.clientHeight,w=a.Ya(d),m=w.left,w=w.top,b.d(d.getBBox,"Function")&&(k=d.getBBox(),p=k.width,k=k.height),"html"===(d.tagName||"").toLowerCase()))p=
Math.max(p,d.clientWidth),k=Math.max(k,d.clientHeight);return{ba:Math.round(100*((g-m)/p)),da:Math.round(100*((r-w)/k)),vc:f.orientation,tc:e,fa:p,X:k}},sa:function(){0!==g.length&&(h.c.b.et=2,h.c.b.ep=g.join("!"),h.c.i(),g=[])}};h.s.e("pv-b",l.ub);return l})();
(function(){var a=mt.lang,b=mt.f,d=mt.event,f=mt.g,e=h.A,s=h.s,g=h.Q,l=g.O,n=+new Date,t=[],q={ka:function(){return function(f){if(h.c&&h.c.Y&&c.aet&&c.aet.length){var d=f.target||f.srcElement;if(d){var g=h.c.Ta,m=b.getAttribute(d,e.Sa)!=x?v:y;if(b.getAttribute(d,e.Ra)==x)if(m)q.ya(q.Ea(d,f));else{var w=b.V(d);if(a.G(g,"*")||a.G(g,w))q.ya(q.Ea(d,f));else for(;d.parentNode!=x;){var m=d.parentNode,w=b.V(m),z="a"===w&&a.G(g,"a")?v:y,w="button"===w&&a.G(g,"button")?v:y,A=b.getAttribute(m,e.Sa)!=x?v:y;
if(b.getAttribute(m,e.Ra)==x&&(z||w||A)){q.ya(q.Ea(m,f));break}d=d.parentNode}}}}}},Ea:function(d,g){var k={},m=e.Qa;k.id=b.getAttribute(d,m.id)||b.getAttribute(d,"id")||"";k.ha=b.getAttribute(d,m.ha)||b.getAttribute(d,"class")||"";k.ga=b.getAttribute(d,m.ga)||b.ma(d);k.content=b.getAttribute(d,m.content)||b.U(d,v);k.ua=b.getAttribute(d,m.ua)||b.V(d);k.link=b.getAttribute(d,m.link)||b.getAttribute(d,"href")||"";k.type=g.type||"click";m=a.cb(d.offsetTop)?d.offsetTop:0;"click"===g.type?m=f.na?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.fb&&g.fb.changedTouches)&&(m=g.fb.changedTouches[0].pageY);k.Fc=m;m=this.Sb(g);k.ba=m.ba||0;k.da=m.da||0;k.fa=m.fa||0;k.X=m.X||0;k.Oa=m.Oa||"b";return k},Sb:function(d){var e=d.target||d.srcElement,g;if(f.na){var m=Math.max(document.documentElement.scrollTop,document.body.scrollTop);g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);g=d.clientX+g;d=d.clientY+m}else g=d.pageX,
d=d.pageY;var w=m=0,z=0,A=0;if(e&&(m=e.offsetWidth||e.clientWidth,w=e.offsetHeight||e.clientHeight,A=b.Ya(e),z=A.left,A=A.top,a.d(e.getBBox,"Function")&&(w=e.getBBox(),m=w.width,w=w.height),"html"===(e.tagName||"").toLowerCase()))m=Math.max(m,e.clientWidth),w=Math.max(w,e.clientHeight);return{ba:Math.round(100*((g-z)/m)),da:Math.round(100*((d-A)/w)),fa:m,X:w,Oa:("a"===(e.tagName||"").toLowerCase()?e:b.Xa(e))?"a":"b"}},ya:function(b){var d=a.h;b=[+new Date-(h.c.$!==u?h.c.$:n),d(b.id),d(b.ha),d(b.ua),
d(b.ga),d(b.link),d(b.content),b.type,b.Fc,b.ba,b.da,b.fa,b.X,b.Oa].join("*");q.za(b);a.d(this.ea(),"Function")&&this.ea()()},za:function(a){a.length>e.P||(encodeURIComponent(t.join("!")+a).length>e.P&&(q.z(t.join("!")),t=[]),t.push(a))},z:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=l(g.B("autoEventTracking"));h.c.i();h.c.b.p=""},ea:function(){return function(){t&&t.length&&(q.z(t.join("!")),t=[])}}};a.H(c.aet)&&""!==c.aet&&s.e("pv-b",function(){d.e(document,"click",q.ka());"ontouchend"in document&&
d.e(window,"touchend",q.ka());d.e(window,"unload",q.ea())});return q})();
(function(){var a=mt.lang,b=mt.event,d=mt.g,f=h.A,e=h.s,s=+new Date,g=[],l=x,n={yb:function(){a.H(c.aet)&&""!==c.aet&&setInterval(n.mb,f.yc)},mb:function(){var a=d.W()+d.M();0<a-h.c.b.vl&&(h.c.b.vl=a)}},t={Kb:function(){return function(){h.c&&(h.c.Y&&c.aet&&c.aet.length)&&(window.clearTimeout(l),l=window.setTimeout(function(){t.xb(d.W()+d.M())},150))}},xb:function(a){t.za([+new Date-(h.c.$!==u?h.c.$:s),a].join("*"))},za:function(a){if(encodeURIComponent(g.join("!")+a).length>f.P||3<g.length)t.z(g.join("!")),
g=[];g.push(a)},z:function(a){n.mb();h.c.b.et=6;h.c.b.vh=d.M();h.c.b.ep=a;h.c.i()},ea:function(){return function(){g&&g.length&&(t.z(g.join("!")),g=[])}}};a.H(c.aet)&&""!==c.aet&&e.e("pv-b",function(){b.e(window,"scroll",t.Kb());b.e(window,"unload",t.ea());n.yb()});return t})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.Ba.Yb()+","+h.Ba.Ub();h.c.b.hca=c.hca;h.c.i()}}function b(){clearTimeout(z);var a;m&&(a="visible"==document[m]);w&&(a=!document[w]);l="undefined"==typeof a?v:a;if((!g||!n)&&l&&t)k=v,r=+new Date;else if(g&&n&&(!l||!t))k=y,p+=+new Date-r;g=l;n=t;z=setTimeout(b,100)}function d(a){var b=document,m="";if(a in b)m=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var f=d[e]+a.charAt(0).toUpperCase()+a.slice(1);
if(f in b){m=f;break}}return m}function f(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))t="focus"==a.type||"focusin"==a.type?v:y,b()}var e=mt.event,s=h.s,g=v,l=v,n=v,t=v,q=+new Date,r=q,p=0,k=v,m=d("visibilityState"),w=d("hidden"),z;b();(function(){var a=m.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,b);e.e(window,"pageshow",b);e.e(window,"pagehide",b);"object"==typeof document.onfocusin?(e.e(document,"focusin",f),e.e(document,"focusout",f)):(e.e(window,
"focus",f),e.e(window,"blur",f))})();h.Ba={Yb:function(){return+new Date-q},Ub:function(){return k?+new Date-r+p:p}};s.e("pv-b",function(){e.e(window,"unload",a())});s.e("duration-send",a());s.e("duration-done",function(){r=q=+new Date;p=0});return h.Ba})();
(function(){var a=mt.lang,b=h.A,d=h.load,f={mc:function(e){if((window._dxt===u||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var f=h.c.T();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),e)}},Ec:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.Ib=f})();
(function(){function a(a,b,d,e){if(!(a===u||b===u||e===u)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var f,g=y,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=d;f[2]=e;a[k]=f.join("*");g=v;break}g||a.push([b,d,e].join("*"));return a.join("!")}}function b(a){for(var d in a)if({}.hasOwnProperty.call(a,d)){var e=a[d];f.d(e,"Object")||f.d(e,"Array")?b(e):a[d]=String(e)}}var d=mt.url,f=mt.lang,e=mt.w,s=mt.g,g=h.A,l=h.s,n=h.Ib,t=h.load,q=h.Aa,r=h.Q,p=r.O,k={aa:[],ta:0,
Ja:y,D:{Pa:"",page:""},init:function(){k.j=0;r.init();l.e("pv-b",function(){k.Jb();k.Lb()});l.e("pv-d",function(){k.Mb();k.D.page=""});l.e("stag-b",function(){h.c.b.api=k.j||k.ta?k.j+"_"+k.ta:"";h.c.b.ct=[decodeURIComponent(q.getData("Hm_ct_"+c.id)||""),k.D.Pa,k.D.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;k.j=0;k.ta=0})},Jb:function(){var a=window._hmt||[];if(!a||f.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var m=arguments[b];
f.d(m,"Array")&&(a.cmd[a.id].push(m),"_setAccount"===m[0]&&(1<m.length&&/^[0-9a-f]{32}$/.test(m[1]))&&(m=m[1],a.id=m,a.cmd[m]=a.cmd[m]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Lb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,e=0,f=b.length;e<f;e++){var g=b[e];d.test(g[0])?k.aa.push(g):k.La(g)}a.cmd[c.id]={push:k.La}},Mb:function(){if(0<k.aa.length)for(var a=0,b=k.aa.length;a<b;a++)k.La(k.aa[a]);k.aa=x},
La:function(a){var b=a[0];if(k.hasOwnProperty(b)&&f.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],y===a||v===a))k.j|=2,h.c.ab=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(k.j|=4,h.c.b.sn=h.c.Za(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=s.W()+s.M(),h.c.b.kb=0,h.c.Ia?(h.c.b.nv=0,h.c.b.st=4):h.c.Ia=v,k.Ja||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=g.protocol+
"//"+document.location.host+a[1],h.c.b.p=p(r.B("pageview")),h.c.i(),h.c.b.p="",h.c.$=+new Date,r.o("pageview"))},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=f.h(a[1])+"*"+f.h(a[2])+(a[3]?"*"+f.h(a[3]):"")+(a[4]?"*"+f.h(a[4]):""),h.c.b.p=p(r.Ga()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){k.ta++;for(var e=(h.c.b.cv||"*").split("!"),g=e.length;g<b-1;g++)e.push("*");e[b-1]=d+"*"+f.h(a[2])+"*"+
f.h(a[3]);h.c.b.cv=e.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?q.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):q.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==u&&b!==u){var e=decodeURIComponent(q.getData("Hm_ct_"+c.id)||""),e=a(e,d,1,b);q.setData("Hm_ct_"+c.id,encodeURIComponent(e),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==u&&b!==u){var e=k.D.Pa,
e=a(e,d,2,b);k.D.Pa=e}}},_setPageTag:function(b){if(!(3>b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==u&&b!==u){var e=k.D.page,e=a(e,d,3,b);k.D.page=e}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],f.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?g.protocol+"//"+window.location.host+a:a,k.Ja=v):k.Ja=y)},_trackOrder:function(a){a=a[1];f.d(a,"Object")&&(b(a),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=p(r.Ga()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];n.mc();n.Ec(a)},_setUserId:function(a){a=a[1];if(a!==u&&(f.H(a)||f.cb(a))){var b=r.B("user").uid_;if(!(b&&b.value===f.h(String(a)))){var b=h.c.b.p,d=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+f.h(String(a));h.c.i();var e={};e.uid_=a;r.setProperty("user",e,v);h.c.b.p=b;h.c.b.ep=d}}},_clearUserId:function(a){1<a.length&&v===a[1]&&r.o("userId")},_setUserProperty:function(a){a=a[1];
f.d(a,"Object")&&r.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&v===a[1]&&r.o("user")},_setSessionProperty:function(a){a=a[1];f.d(a,"Object")&&r.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&v===a[1]&&r.o("session")},_setPageviewProperty:function(a){a=a[1];f.d(a,"Object")&&r.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&v===a[1]&&r.o("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];f.d(a,"Object")&&r.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&v===a[1]&&r.o("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],y===a||v===a))h.c.bb=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],y===a||v===a))h.c.Y=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):l.K("duration-send");l.K("duration-done")},_require:function(a){1<a.length&&(a=a[1],g.Ab.test(d.L(a))&&t(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,d=a[1];a=a[2];if(f.G(g.ib,d)&&f.d(a,"Function")&&(b.plugins=b.plugins||{},b.I=b.I||{},b.plugins[d]=a,b.C=b.C||[],a=b.C.slice(),d&&a.length&&a[0][1]===d))for(var e=0,k=a.length;e<k;e++){var l=a[e][2]||{};if(b.plugins[d]&&!b.I[d])b.I[d]=new b.plugins[d](l),b.C.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],e=a[2]||{};if(f.G(g.ib,d))if(b.plugins=b.plugins||{},b.I=b.I||{},b.plugins[d]&&!b.I[d])b.I[d]=new b.plugins[d](e);else{b.C=b.C||
[];for(var e=0,l=b.C.length;e<l;e++)if(b.C[e][1]===d)return;b.C.push(a);k._require([x,g.uc+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];f.d(a,"Object")||(a={});a._iden=b;r.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=p(r.B("customEvent"));h.c.i();h.c.b.p="";r.o("customEvent")}}};k.init();h.Bb=k;return h.Bb})();
(function(){var a=h.s;c.spa!==u&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=v,this.b={},this.bb=this.ab=v,this.Y=k.Y,this.Ta=e.H(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Ia=y,this.init())}var b=mt.url,d=mt.pb,f=mt.Na,e=mt.lang,s=mt.cookie,g=mt.g,l=mt.sessionStorage,n=mt.w,t=mt.event,q=h.Aa,r=h.Q,p=r.O,k=h.A,m=h.load,w=h.s;a.prototype={Z:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},qa:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},oa:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.qa(a,c.dm[d]))return v}else{var e=b.L(a);if(e&&this.Z(e,c.dm[d]))return v}return y},T:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.Z(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},la:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.qa(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},ac:function(){if(!document.referrer)return k.J-k.N>c.vdur?1:4;var a=y;this.oa(document.referrer)&&this.oa(document.location.href)?a=v:(a=b.L(document.referrer),a=this.Z(a||"",document.location.hostname));return a?k.J-k.N>c.vdur?1:4:3},Cc:function(){var a,b,d,e,f,g;k.N=q.getData("Hm_lpvt_"+c.id)||0;13===k.N.length&&(k.N=Math.round(k.N/1E3));b=this.ac();a=4!==b?1:0;if(g=q.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.J-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.J);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.J,e="",f=1;this.qc()?(q.setData("Hm_lvt_"+c.id,g,c.age),q.setData("Hm_lpvt_"+c.id,k.J),d=s.sc(this.T(),this.la())):this.Nb();if(0===c.nv&&this.oa(document.location.href)&&(""===document.referrer||this.oa(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},qc:function(){var a=b.L(document.location.href);return!e.G("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},Nb:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&q.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&q.removeData(d[0])}},nb:function(){for(var a=[],b=this.b.et,d=0,e=k.qb.length;d<e;d++){var f=k.qb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},Dc:function(){this.Cc();
this.b.si=c.id;this.b.sn=this.Za();this.b.su=document.referrer;this.b.ds=g.xc;this.b.cl=g.colorDepth+"-bit";this.b.ln=String(g.language).toLowerCase();this.b.ja=g.javaEnabled?1:0;this.b.ck=g.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=f.dc();this.b.v="1.2.76";this.b.cv=decodeURIComponent(q.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=g.W()+g.M();var a=document.location.href;this.b.cm=b.m(a,k.ic)||"";this.b.cp=b.m(a,k.jc)||b.m(a,k.Ic)||"";this.b.cw=b.m(a,
k.hc)||b.m(a,k.Kc)||"";this.b.ci=b.m(a,k.fc)||b.m(a,k.Hc)||"";this.b.cf=b.m(a,k.kc)||b.m(a,k.Jc)||"";this.b.cu=b.m(a,k.gc)||b.m(a,k.Gc)||"";this.b.u=window.location.href},init:function(){try{this.Dc(),0===this.b.nv?this.Bc():this.Va(),h.c=this,this.Db(),this.Cb(),w.K("pv-b"),this.zc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.ra+"//"+k.Ma+"?"+b.join("&"))}},zc:function(){function a(){w.K("pv-d")}
this.ab?(this.Ia=v,this.b.et=0,this.b.ep="",this.b.p=p(r.B("pageview")),this.b.vl=g.W()+g.M(),this.i(a),this.b.p=""):a();this.$=+new Date;r.o("pageview")},i:function(a){if(this.bb){var b=this;b.b.rnd=Math.round(Math.random()*k.ca);b.b.r=g.orientation;b.b.ww=g.tb;w.K("stag-b");var f=k.ra+"//"+k.Ma+"?"+b.nb();w.K("stag-d");b.zb(f);d.log(f,function(d){b.lb(d);e.d(a,"Function")&&a.call(b)})}},Db:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=b.L(document.referrer)===k.rb?1:0,f=
b.m(a,"jn"),g=/^select$/.test(f);a&&(d.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.ca),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},Cb:function(){try{if(window.postMessage&&window.self!==window.parent){var a=this;t.e(window,"message",function(d){if(b.L(d.origin)===k.rb){d=d.data||{};
var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.ca),m(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},zb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,
n.stringify(b))},lb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,n.stringify(b)):this.Va()}},Va:function(){l.remove("Hm_unsent_"+c.id)},Bc:function(){var a=this,b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length)for(var f=function(b){d.log(k.ra+"//"+b,function(b){a.lb(b)})},
g=0;g<b.length;g++)f(b[g])},Za:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.A,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var a=mt.g,b=mt.lang,d=mt.event,f=mt.w;if("undefined"!==typeof h.c&&(c.med||(!a.na||7<a.Wb())&&c.cvcc)){var e,s,g,l,n=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},t=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===y)return y},q=function(a,d){var k={};k.n=e;k.t="clk";k.v=a;if(d){var l=d.getAttribute("href"),n=d.getAttribute("onclick")?""+d.getAttribute("onclick"):x,p=d.getAttribute("id")||"";g.test(l)?(k.sn=
"mediate",k.snv=l):b.d(n,"String")&&g.test(n)&&(k.sn="wrap",k.snv=n);k.id=p}h.c.b.et=86;h.c.b.ep=f.stringify(k);h.c.i();for(k=+new Date;400>=+new Date-k;);};if(c.med)s="/zoosnet",e="swt",g=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f=0,k=b.length;f<k;f++)d=b[f],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(g.test(e)||g.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){s="/other-comm";e="other";g=c.cvcc.q||u;var r=c.cvcc.id||u;l={click:function(){for(var a=[],b=n(document.getElementsByTagName("a")),b=[].concat.apply(b,n(document.getElementsByTagName("area"))),b=[].concat.apply(b,n(document.getElementsByTagName("img"))),d,e,f,k=0,l=b.length;k<l;k++)d=b[k],g!==u?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),r?(d=d.getAttribute("id"),(g.test(e)||
g.test(f)||r.test(d))&&a.push(b[k])):(g.test(e)||g.test(f))&&a.push(b[k])):r!==u&&(d=d.getAttribute("id"),r.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof l&&"undefined"!==typeof g){var p;s+=/\/$/.test(s)?"":"/";var k=function(a,d){if(p===d)return q(s+a,d),y;if(b.d(d,"Array")||b.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(p===d[e])return q(s+a+"/"+(e+1),d[e]),y};d.e(document,"mousedown",function(a){a=a||window.event;p=a.target||a.srcElement;var d={};for(t(l,function(a,e){d[a]=b.d(e,
"Function")?e():document.getElementById(e)});p&&p!==document&&t(d,k)!==y;)p=p.parentNode})}}})();(function(){var a=mt.f,b=mt.lang,d=mt.event,f=mt.w;if("undefined"!==typeof h.c&&b.d(c.cvcf,"Array")&&0<c.cvcf.length){var e={wb:function(){for(var b=c.cvcf.length,f,l=0;l<b;l++)(f=a.Wa(decodeURIComponent(c.cvcf[l])))&&d.e(f,"click",e.Ca())},Ca:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=f.stringify(a);h.c.i()}}};a.jb(function(){e.wb()})}})();
(function(){var a=mt.event,b=mt.w;if(c.med&&"undefined"!==typeof h.c){var d={n:"anti",sb:0,kb:0,clk:0},f=function(){h.c.b.et=86;h.c.b.ep=b.stringify(d);h.c.i()};a.e(document,"click",function(){d.clk++});a.e(document,"keyup",function(){d.kb=1});a.e(window,"scroll",function(){d.sb++});a.e(window,"load",function(){setTimeout(f,5E3)})}})();c.oc!==u&&"1"===String(c.oc)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","OcpcCbHm"]));})();
